### ISSUE TITLE
Passive Component Generation Asynchronous Properties

### ISSUE THREAD

**Issue by AaronMcDaniel** [SterlingPeet/cookiecutter-fprime-component#1]
When a passive component is generated, ports and commands default to being asynchronous, but everything must be synchronous in a passive component, so the configuration is invalid. I believe that all components can have synchronous ports and commands, so defaulting those to synchronous instead of asynchronous would probably fix the issue

**Comment by SterlingPeet** [comment]
Good catch, I think we do a little better by changing the other port's synchronicity based on the active/passive variable.  I'll look into it soon.
