### ISSUE TITLE
Selectable multi-platform Support

### ISSUE THREAD

**Issue by SterlingPeet** [SterlingPeet/cookiecutter-fprime-component#2]
Turns out, a lot of components do not need multi-platform support, especially if they are not drivers.  Make multi-platform support an option that defaults to ``no``.

**Comment by nathancheek** [comment]
Related to the multi-platform support, it looks like `CMakeLists.txt` adds the `AVR` file if `CMAKE_SYSTEM_NAME_LOWER` = `arduino`, even though an `Arduino` file is created.

**Comment by SterlingPeet** [comment]
Noted.  I'll sweep that into this issue when it is fixed.
