### ISSUE TITLE
README component_dir_name field description

### ISSUE THREAD

**Issue by nathancheek** [SterlingPeet/cookiecutter-fprime-component#4]
Currently the README has no description of the required `component_dir_name` field. It would be good to include information here about whether `Component` should be appended or not (it currently is by default).

**Comment by SterlingPeet** [comment]
Heh, so, the current defacto standard seems to be yes, do append it.  I have already changed that default in my updated version (``devel`` branch), but I want to keep the function for people that generate a template against an existing component (e.g. to get the docs folder contents).  I'll make a note in the cookiecutter docs to point out that the normally expected answer for new components is "yes".

**Comment by SterlingPeet** [comment]
Text for the docs:

The general convention is for F Prime components to have the ``Component`` suffix for file names and class names.  While it is not required, the Autocoder will assume this format, and Autocoder provided templates may be more difficult to adapt if this is not selected.
