### ISSUE TITLE
Ping port is always async_input even when component is passive

### ISSUE THREAD

**Issue by nathancheek** [SterlingPeet/cookiecutter-fprime-component#5]
The input kind on this line should be changed based on whether the component is passive or not, since passive components cannot have inputs of kind `async_input`.

https://github.com/SterlingPeet/cookiecutter-fprime-component/blob/f8315d5168b41b7db73867d4b18df66953b83839/%7B%7Bcookiecutter.component_dir_name%7D%7D/%7B%7Bcookiecutter.component_class_name%7D%7DAi.xml#L10

Similarly, this should be changed to `sync` when the component is passive.

https://github.com/SterlingPeet/cookiecutter-fprime-component/blob/f8315d5168b41b7db73867d4b18df66953b83839/%7B%7Bcookiecutter.component_dir_name%7D%7D/%7B%7Bcookiecutter.component_class_name%7D%7DAi.xml#L24

**Comment by SterlingPeet** [comment]
See Issue #1.

**Comment by nathancheek** [comment]
Oops yes, this is a duplicate.
