### ISSUE TITLE
Asynchronous command generated for passive component

### ISSUE THREAD

**Issue by nathancheek** [SterlingPeet/cookiecutter-fprime-component#7]
Even when a passive component type is selected, an `async` command is generated in the `ComponentAi.xml` file. This causes `fprime-util impl` to fail, when following the instructions at the bottom of the README.

While the user will probably need to update the XML boilerplate anyway, it would still be more beginner-friendly to set this command type as `sync` if passive component type is selected, allowing `fprime-util impl` to actually run on the given boilerplate.

**Comment by SterlingPeet** [comment]
Are you expecting something like [this](https://github.com/SterlingPeet/cookiecutter-fprime-component/blob/89826c9c7225f8991955fa6d4b57c2bc9726818c/%7B%7Bcookiecutter.component_dir_name%7D%7D/%7B%7Bcookiecutter.component_slug%7D%7DComponentAi.xml#L13):

            <port name="PingIn" data_type="Svc::Ping" kind="sync_input" max_number="1">

**Comment by SterlingPeet** [comment]
Or are you looking at [this line](https://github.com/SterlingPeet/cookiecutter-fprime-component/blob/89826c9c7225f8991955fa6d4b57c2bc9726818c/%7B%7Bcookiecutter.component_dir_name%7D%7D/%7B%7Bcookiecutter.component_slug%7D%7DComponentAi.xml#L28)?

**Comment by nathancheek** [comment]
The second one, yes.

**Comment by SterlingPeet** [comment]
ok, fix incoming.
